# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1.1

# Select what we should cache between builds
cache:
  paths:
  - vendor/

stages:
  - test
  - release


# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  stage: test
  script:
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

release:
  stage: release
  script:
  - rm -f composer.phar phpunit.xml README composer.lock composer.json
  - rm -rf .git
  - rm -rf tests
  - rm -rf tests

  artifacts:
    paths:
      - ./